package main

var optionsSport = []string{
	"AlpineSki",
	"BackcountrySki",
	"Canoeing",
	"Crossfit",
	"EBikeRide",
	"Elliptical",
	"Handcycle",
	"Hike",
	"IceSkate",
	"InlineSkate",
	"Kayaking",
	"Kitesurf",
	"NordicSki",
	"Ride",
	"RockClimbing",
	"RollerSki",
	"Rowing",
	"Run",
	"Snowboard",
	"Snowshoe",
	"StairStepper",
	"StandUpPaddling",
	"Surfing",
	"Swim",
	"VirtualRide",
	"VirtualRun",
	"Walk",
	"WeightTraining",
	"Wheelchair",
	"Windsurf",
	"Workout",
	"Yoga",
}

var optionsVisibility = []string{"only_me", "followers_only", "everyone"}
